---
version: 2
enable-beta-ecosystems: true

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: ci
    reviewers:
      - vipyrsec/devops
    assignees:
      - vipyrsec/devops

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: deps(docker)
    reviewers:
      - vipyrsec/devops
    assignees:
      - vipyrsec/devops

  - package-ecosystem: uv
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: deps(python)
    reviewers:
      - vipyrsec/devops
    assignees:
      - vipyrsec/devops
    groups:
      prod:
        dependency-type: production
        applies-to: version-updates
      dev:
        dependency-type: development
        applies-to: version-updates
